[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor
monitor_speed = 115200

; Configurações de Memória (Octal PSRAM para Freenove WROOM CAM N16R8)
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB

; Flag para habilitar PSRAM no ESP32-S3
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=2

; Bibliotecas Necessárias
lib_deps = 
    adafruit/Adafruit MLX90640 @ ^1.0.2
    rfetick/MPU6050_tockn @ ^1.5.2
    teemuatlut/TMC2209Stepper @ ^0.9.1
    thotro/arduino-dw1000 @ ^0.9
